name:                aitsi
version:             0.1.0.0
github:              "Swordlash/AiTSI"
license:             BSD3
author:              "Mateusz Goslinowski"
maintainer:          "mateusz.goslinowski@gmail.com"
copyright:           "2022 Mateusz Goslinowski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Swordlash/AiTSI#README.md>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- persistent
- persistent-postgresql
- esqueleto
- text
- monad-logger
- mtl
- bytestring
- bcrypt
- cryptonite

default-extensions:
- OverloadedStrings
- GeneralizedNewtypeDeriving
- DeriveGeneric
- DerivingStrategies
- DeriveAnyClass
- TemplateHaskell
- TypeFamilies
- GADTs
- StandaloneDeriving
- UndecidableInstances
- FlexibleInstances
- DataKinds
- MultiParamTypeClasses
- QuasiQuotes
- RankNTypes


library:
  source-dirs: src

executables:
  aitsi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aitsi

tests:
  aitsi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aitsi
